apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
spec:
  selector:
    app: catalogue
  ports:
    - protocol: TCP
      port: {{ .Values.service.servicePort }}
      targetPort: 8080